### ISSUE TITLE
Real issue : "HttpError: Bad credentials"

### ISSUE THREAD

**Issue by Ameausoone** [TejasvOnly/random-rickroll#29]
For a demo, I have include `TejasvOnly/random-rickroll` github action here : https://github.com/Ameausoone/demo-github-action/blob/main/.github/workflows/new-issue.yaml

```
on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Rick Roll
        uses: TejasvOnly/random-rickroll@v1.0
        with:
          percentage: 100
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
      - name: Answer with HowDoI
        uses: ameausoone/howdoi-action@v1.x
```

When a user create an issue, Github action is triggered, but I got this error : 

https://github.com/Ameausoone/demo-github-action/runs/4162701030?check_suite_focus=true#step:3:1

```
Run TejasvOnly/random-rickroll@v1.0
  with:
    percentage: 100
    GITHUB_TOKEN: ***'
Gottem!!
(node:1888) UnhandledPromiseRejectionWarning: HttpError: Bad credentials
    at /home/runner/work/_actions/TejasvOnly/random-rickroll/v1.0/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
